pipeline:
  projectIdentifier: Nic_Sandbox
  orgIdentifier: SE_Sandbox
  tags: {}
  stages:
    - stage:
        name: Plugin Testing
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Surge
                  identifier: Surge
                  spec:
                    connectorRef: Nics_Registry
                    image: docker.io/lovellfelix/surge.sh-ci
                    shell: Sh
                    command: |-
                      /bin/entrypoint.sh

                      export ARTIFACT_URL="https://${SURGE_PROJECT_DOMAIN}.surge.sh"
                    envVariables:
                      SURGE_ACT_TOKEN: <+secrets.getValue(“project.NicA_Surge_Token”)>
                      SURGE_ACT_EMAIL: nicolas.acton@harness.io
                      SURGE_PROJECT_DOMAIN: harness-artifact
                    outputVariables:
                      - name: ARTIFACT_URL
                  description: Creates a surge.sh website
              - step:
                  type: Plugin
                  name: Register Artifact
                  identifier: create_artifact
                  spec:
                    connectorRef: Nics_Registry
                    image: tuffacton/registerartifact
                  description: Registers an arbitrary artifact URI in a pipeline execution.
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        variables:
          - name: PLUGIN_ARTIFACT_FILE
            type: String
            description: ""
            value: /addon/tmp/.plugin/artifact
  properties:
    ci:
      codebase:
        connectorRef: account.Public_Github
        repoName: cloudacademy/static-website-example
        build: <+input>
  identifier: Artifact_Registration
  name: Artifact Registration
