pipeline:
  projectIdentifier: Nic_Sandbox
  orgIdentifier: SE_Sandbox
  tags: {}
  stages:
    - stage:
        name: Plugin Testing
        identifier: Build
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Find Artifact
                  identifier: Find_Artifact
                  spec:
                    connectorRef: Nics_Registry
                    image: ubuntu:22.04
                    shell: Sh
                    command: |-
                      export PLUGIN_ARTIFACT_URL=https://www.amazon.com/
                      echo "PLUGIN_ARTIFACT_URL = $PLUGIN_ARTIFACT_URL"
                      export ARTIFACT_URL=https://www.amazon.com/
                      echo "ARTIFACT_URL = $ARTIFACT_URL"
                      export ARTIFACT_NAME=Amazon
                      echo "ARTIFACT_NAME = $ARTIFACT_NAME"
                      export PLUGIN_ARTIFACT_NAME=Amazon
                      echo "PLUGIN_ARTIFACT_NAME = $PLUGIN_ARTIFACT_NAME"
                    envVariables:
                      TEST: TEST
                    outputVariables:
                      - name: PLUGIN_ARTIFACT_URL
                      - name: ARTIFACT_URL
                      - name: ARTIFACT_NAME
                      - name: PLUGIN_ARTIFACT_NAME
                      - name: TEST
              - step:
                  type: Run
                  name: Variable Test
                  identifier: Variable_Test
                  spec:
                    connectorRef: Nics_Registry
                    image: ubuntu:22.04
                    shell: Sh
                    command: |-
                      echo <+pipeline.stages.Build.spec.execution.steps.Find_Artifact.output.outputVariables.TEST>

                      echo $TEST
                    envVariables:
                      TEST: <+steps.Find_Artifact.outputVariables.PLUGIN_ARTIFACT_URL>
                  description: Test to make sure variables are registering
              - step:
                  type: Plugin
                  name: Register Artifact
                  identifier: create_artifact
                  spec:
                    connectorRef: Nics_Registry
                    image: tuffacton/registerartifact
                    settings:
                      plugin_artifact_url: <+steps.Find_Artifact.output.outputVariables.PLUGIN_ARTIFACT_URL>
                      artifact_url: <+steps.Find_Artifact.output.outputVariables.ARTIFACT_URL>
                      artifact_name: <+steps.Find_Artifact.output.outputVariables.ARTIFACT_NAME>
                      plugin_artifact_name: <+steps.Find_Artifact.output.outputVariables.PLUGIN_ARTIFACT_NAME>
                    entrypoint:
                      - /build.sh
                    imagePullPolicy: Always
                  description: Registers an arbitrary artifact URI in a pipeline execution.
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.SE_Sandbox
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        variables:
          - name: PLUGIN_ARTIFACT_FILE
            type: String
            description: ""
            value: /addon/tmp/.plugin/artifact
  identifier: Artifact_Registration
  name: Artifact Registration
