pipeline:
  projectIdentifier: Nic_Sandbox
  orgIdentifier: SE_Sandbox
  tags: {}
  stages:
    - stage:
        name: Plugin Testing
        identifier: Build
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Find Artifact
                  identifier: Find_Artifact
                  spec:
                    shell: Sh
                    command: |-
                      export PLUGIN_ARTIFACT_URL=https://www.google.com
                      export PLUGIN_NAME=Google
              - step:
                  type: Plugin
                  name: Register Artifact
                  identifier: create_artifact
                  spec:
                    connectorRef: Nics_Registry
                    image: tuffacton/registerartifact
                    imagePullPolicy: Always
                  description: Registers an arbitrary artifact URI in a pipeline execution.
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: org.SE_Sandbox
              namespace: harness-delegate-ng
              nodeSelector: {}
              os: Linux
        variables:
          - name: PLUGIN_ARTIFACT_FILE
            type: String
            description: ""
            value: /addon/tmp/.plugin/artifact
          - name: PLUGIN_ARTIFACT_URL
            type: String
            description: ""
            value: https://www.google.com
          - name: PLUGIN_ARTIFACT_NAME
            type: String
            description: ""
            value: Google
  identifier: Artifact_Registration
  name: Artifact Registration
