pipeline:
  projectIdentifier: Nic_Sandbox
  orgIdentifier: SE_Sandbox
  tags: {}
  stages:
    - stage:
        name: Plugin Testing
        identifier: Build
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Find Artifact
                  identifier: Find_Artifact
                  spec:
                    shell: Sh
                    command: |-
                      export ARTIFACT_URL=https://www.google.com
                      export NAME=Google
              - step:
                  type: Plugin
                  name: Register Artifact
                  identifier: create_artifact
                  spec:
                    connectorRef: Nics_Registry
                    image: tuffacton/registerartifact
                  description: Registers an arbitrary artifact URI in a pipeline execution.
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        variables:
          - name: PLUGIN_ARTIFACT_FILE
            type: String
            description: ""
            value: /addon/tmp/.plugin/artifact
  identifier: Artifact_Registration
  name: Artifact Registration
